### PR TITLE
Address issue #58

### LINKED ISSUE #58: basic auth - potential security issue if wrongly configured
During reviewing #54 (and experimenting with it), I just remarked that a wrong configuration of `OC_User_BasicAuth` could lead to a potential security issue:

If an admin configures an URL to authenticate against, where no basic authentication happens at all but the server responds with a 200 response immediately on each request, everyone can login with any username/password combinations.
It's even possible to login with usernames registered under other backends (e.g. a username registered as a regular Nextcloud user; you can just use anything as password and get access to this user account as well).

It could even be the case, that something changes on the side of the requested web server over time and the admin wouldn't remark it at all (that his Nextcloud is open to anyone) until he/she explicitly tests wrong username/password combinations

I wonder, if we could somehow check, if the requested web server does an authentication at all and otherwise not allow access. If not, we should at least add a warning to the documentation. 
What do you think @nerdmaennchen ?

### PR DESCRIPTION
**Pull request by alejandroliu**
Signed-off-by: Alejandro Liu <alejandro_liu@hotmail.com>

Fixes #58 

Changes proposed in this pull request:
 - Perform an initial check to prevent misconfigured Basic Auth URLs

This PR introduces an additional request in the BasicAuth external backend to check if the
provided URL is performing authentication.

The performance hit of the additional request is quite minor, as it only happens during session
login.  And doesn't happen again until the session logs out.

### CODE REVIEW

**Comment by nerdmaennchen** [comment]
Sorry for my late review.
From what I (now) know: You are absolutely correct.
Testing for that header should prevent arbitrary user/pw combinations from logging in when authenticating agains a misconfigured URL.

Im not sure if a second request is actually necessary though.
Correct me if I'm wrong, but wouldn't it be enough to test the response of the authentication request for the presence of the www-authenticate header?
If so, a single request would suffice and the performance penalty (I agree with you here, I'd say it is miniscule) would be even further reduced.

Anyways, thank you very much for you contribution!

All the best,
Lutz

**Comment by violoncelloCH** [comment]
@alejandroliu thank you for your contribution!
@nerdmaennchen @alejandroliu I just have done a little research on this myself (and also some tests)... It seems basicauth is designed to not send anything on a correct authentication, so it looks like it's not possible to only do one request... 
so this implementation is probably the best we can do, if we want a check (performance losses or not)...

File: lib/basicauth.php [hunk 1]
```diff
@@ -24,6 +24,31 @@ public function __construct($authUrl) {
...
+		/*
+		 * Connect without user/name password to make sure
+		 * URL is indeed authenticating or not...
+		 */
+		stream_context_set_default(array(
+		  'http'=>array(
+		    'method'=>"GET",
+		  ))
+		);
+		$headers = get_headers($this->authUrl, 1);
```
Comment (violoncelloCH) [inline lib/basicauth.php]: could you use an other variable name here for the headers for this check? (so we can make sure this is never mixed up with the real auth request somehow)

File: lib/basicauth.php [hunk 2]
```diff
@@ -24,6 +24,31 @@ public function __construct($authUrl) {
...
+		if(!$headers) {
+			OC::$server->getLogger()->error(
+				'ERROR: Not possible to connect to BasicAuth Url: '.$this->authUrl,
+				['app' => 'user_external']
+			);
+			return false;
+		}
+		if (!isset($headers['WWW-Authenticate'])) {
+			OC::$server->getLogger()->error(
+				'ERROR: Mis-configured BasicAuth Url: '.$this->authUrl,
```
Comment (violoncelloCH) [inline lib/basicauth.php]: could you add a little extra info here for the admin, so it's clear why the Url is not accepted? (something like `This Url doesn't validate users properly!`)

File: lib/basicauth.php (hunk 1 above)
Comment (alejandroliu) [reply lib/basicauth.php]: Renamed the variable to $canary.

File: lib/basicauth.php (hunk 2 above)
Comment (alejandroliu) [reply lib/basicauth.php]: Added text saying that the URL does not do authentication.

**Comment by violoncelloCH** [comment]
@nerdmaennchen feel free to merge, if you agree with this :)

File: lib/basicauth.php [hunk 3]
```diff
@@ -24,6 +24,31 @@ public function __construct($authUrl) {
...
+		);
+		$canary = get_headers($this->authUrl, 1);
+		if(!$canary) {
+			OC::$server->getLogger()->error(
+				'ERROR: Not possible to connect to BasicAuth Url: '.$this->authUrl,
+				['app' => 'user_external']
+			);
+			return false;
+		}
+		if (!isset($canary['WWW-Authenticate'])) {
```
Comment (nerdmaennchen) [inline lib/basicauth.php]: That should do the trick:

if (!isset(array_change_key_case($headers, CASE_LOWER)['www-authenticate'])) {
...

Comment (violoncelloCH) [reply lib/basicauth.php]: yes, that's probably the better way than looping...

Comment (alejandroliu) [reply lib/basicauth.php]: Adjusted the check so that it is case insensitve.

**Comment by alejandroliu** [comment]
Are there any pending issues?
